@startuml
left to right direction

actor Guest
actor Student
actor Teacher
actor Admin

Teacher --|> Student
Admin --|> Teacher

rectangle STEMgraph {

  usecase "Login/Registration" as Login
  usecase "View Whole Graph" as ViewGraph
  usecase "Select ToDo/Finished Node" as SelectNode
  usecase "Open Lesson Link" as OpenLesson
  usecase "View Subgraph" as ViewSub
  usecase "Mark Node as ToDo/Finished" as MarkNode

  usecase "Save Progress in LocalStorage" as SaveLocal
  usecase "Save Progress in Keycloak DB" as SaveKeycloak

  usecase "Temporary Stats" as StatsTemp
  usecase "View Profile" as ViewProfile

  usecase "Create Learning Path" as CreatePath
  usecase "Edit Learning Path" as EditPath
  usecase "View Student Progress" as ViewStudentProgress

  usecase "Update Graph" as UpdateGraph
  usecase "Manage Nodes" as ManageNodes
  usecase "Manage Users" as ManageUsers

  SelectNode ..> ViewGraph     : <<extend>>
  OpenLesson ..> SelectNode    : <<extend>>
  ViewSub    ..> SelectNode    : <<extend>>
  MarkNode   ..> SelectNode    : <<extend>>

  ' INCLUDE mit Bedingungen
  MarkNode ..> SaveLocal       : <<include>> (Guest)
  MarkNode ..> SaveKeycloak    : <<include>> (Student)
}

' Associations
Guest --> Login
Guest --> ViewGraph
Guest --> StatsTemp

Student --> Login
Student --> ViewGraph
Student --> ViewProfile

Teacher --> CreatePath
Teacher --> EditPath
Teacher --> ViewStudentProgress

Admin --> UpdateGraph
Admin --> ManageNodes
Admin --> ManageUsers

@enduml